export const RECORDS_ASC = 'recordsAsc'
export const RECORDS_DESC = 'recordsDesc'
export const CREATION_DATE_ASC = 'creationDateAsc'
export const CREATION_DATE_DESC = 'creationDateDesc'
export const DUE_DATE_ASC = 'dueDateAsc'
export const DUE_DATE_DESC = 'dueDateDesc'
